# TODO удалить docker-compose up -d --no-deps --build

version: '3.3'
services:

  backend:
    env_file: ../.env
    build:
      context: ../backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../frontend/
        target: /app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ../frontend/build
        target: /usr/share/nginx/html/
      - type: bind
        source: ../docs/
        target: /usr/share/nginx/html/api/docs/
      - type: bind
        source: ../backend/backend_static
        target: /usr/share/nginx/html/static/
