# Generated by Django 3.2 on 2023-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
