# Generated by Django 3.2 on 2023-04-24 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20230424_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favorites',
        ),
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_favorite',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_favorites'),
        ),
    ]
