# Generated by Django 3.2 on 2023-05-05 03:52

from django.db import migrations, models
import django.db.models.expressions
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230428_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Выбирите цвет', max_length=20, null=True, unique=True, validators=[recipes.validators.validate_hex_color], verbose_name='Цвет в НЕХ'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='user_cant_follow_self'),
        ),
    ]
