# Generated by Django 3.2 on 2023-05-03 12:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230503_1913'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cant_follow_myself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='user_cant_follow_self'),
        ),
    ]
