# Generated by Django 3.2 on 2023-05-03 13:04

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230503_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='Выбирите цвет', max_length=20, null=True, unique=True, validators=[recipes.validators.validate_hex_color], verbose_name='Цвет в НЕХ'),
        ),
    ]
