# Generated by Django 3.2 on 2023-07-24 15:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Проверьте правильность написания никнейма', regex=re.compile('^[\\w.@+-]+\\Z'))], verbose_name='Логин'),
        ),
    ]
