# Generated by Django 3.2 on 2023-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230428_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodgram',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
