# Generated by Django 3.2 on 2023-06-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                max_length=7, unique=True, verbose_name="Цвет"),
        ),
    ]
