# Generated by Django 3.2 on 2023-12-02 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231201_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Принимаются слова из букв', regex='[a-z]+')], verbose_name='Название'),
        ),
    ]
