# Generated by Django 3.2 on 2023-07-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230706_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='recipes.recipes', verbose_name='id рецепта')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='recipes.tag', verbose_name='id тега')),
            ],
            options={
                'verbose_name': 'Тег рецепта',
                'verbose_name_plural': 'Теги рецепта',
            },
        ),
    ]
