# Generated by Django 2.2.16 on 2022-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220929_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя тега'),
        ),
    ]
