# Generated by Django 3.2.3 on 2023-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230616_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тэга', max_length=200, unique=True, verbose_name='Название тэга')),
                ('color', models.CharField(help_text='Введите код цвета тэга', max_length=7, null=True, unique=True, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(help_text='Введите слаг тэга', unique=True, verbose_name='Слаг тэга')),
            ],
        ),
    ]
