# Generated by Django 3.2 on 2023-07-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipestags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipesTags',
        ),
    ]
