# Generated by Django 3.2 on 2023-11-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20231124_1122'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique user recipe',
        ),
    ]
