# Generated by Django 3.2 on 2023-11-24 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_favorite_unique user recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Приветствуется человекочитаемоеназвание рецепта', regex='[^!@#$%^&*()_0-9]')], verbose_name='Название'),
        ),
    ]
