# Generated by Django 3.2 on 2023-07-01 12:28

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.IntegerField(default=1, error_messages={'invalid': 'Добавьте хотя бы 1 ингридиент'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество ингридиентов'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default=1, error_messages={'invalid': 'Время готовки от 1 до 1000 минут.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.validate_hex_color], verbose_name='Цвет'),
        ),
    ]
