# Generated by Django 3.2 on 2023-06-23 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_subcribed",
        ),
    ]
