# Generated by Django 5.0.4 on 2024-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True, verbose_name='Электронная Почта'),
        ),
    ]
