# Generated by Django 3.2.3 on 2023-06-15 09:25

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(help_text='Введите адрес email', max_length=254, unique=True, verbose_name='Адрес email'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='first_name',
            field=models.CharField(help_text='Введите своё имя', max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию', max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.CharField(help_text='Введите пароль', max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Логин пользователя занят'}, help_text='Введите свой логин', max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Логин пользователя, username'),
        ),
    ]
