# Generated by Django 5.0.4 on 2024-04-19 08:08

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_.+-]+$'), users.models.username_validaor], verbose_name='Имя Пользователя'),
        ),
    ]
