# Generated by Django 5.0.4 on 2024-04-19 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator('Недопустимый email')], verbose_name='Электронная Почта'),
        ),
    ]
